"""empty message

Revision ID: 2fc87b13498f
Revises: 
Create Date: 2017-11-04 18:37:08.758154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc87b13498f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squash_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('squash_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Unicode(), nullable=True),
    sa.Column('loser', sa.Unicode(), nullable=True),
    sa.Column('score1', sa.Unicode(), nullable=True),
    sa.Column('score2', sa.Unicode(), nullable=True),
    sa.Column('score3', sa.Unicode(), nullable=True),
    sa.Column('score4', sa.Unicode(), nullable=True),
    sa.Column('score5', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('squash_tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opp_school', sa.Unicode(), nullable=True),
    sa.Column('location', sa.Unicode(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('squash_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(), nullable=True),
    sa.Column('last_name', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squash_user')
    op.drop_table('squash_tournament')
    op.drop_table('squash_match')
    op.drop_table('squash_admin')
    # ### end Alembic commands ###
